stages:
  - build
  - deploy


build project:
  stage: build
  image: node
  script:
    - npm install
    - npm start
    - npm build
  artifacts:
    paths:
      - build/ 

netlify:
  stage: deploy
  image: node
  script:
    - npm install -g netlify-cli
    - netlify deploy --dir=build --prod
