stages:
  - test
  - build
  - deploy

test project:
  stage: test
  image: node:15
  script:
    - yarn install
    - yarn test
    
build project:
  stage: build
  image: node:15
  script:
    - yarn start
    - yarn build
  artifacts:
    paths:
      - build/ 

netlify:
  stage: deploy
  image: node:15
  script:
    - npm install -g netlify-cli
    - netlify deploy --dir=build --prod
