stages:
  - build
  - deploy


    
build project:
  stage: build
  image: node
  script:
    - yarn start
    - yarn build
  artifacts:
    paths:
      - build/ 

netlify:
  stage: deploy
  image: node
  script:
    - yarn install -g netlify-cli
    - netlify deploy --dir=build --prod
